services:
  frontend:
    command: ["deno", "run", "dev", "--host", "0.0.0.0"]
    build:
      target: "frontend"
    ports:
      - "127.0.0.1:8000:5173"
    volumes:
      - "./frontend/src:/app/src:ro"
      - "./frontend/css:/app/css:ro"
      - "./frontend/public:/app/public:ro"
      - "./shared:/app/shared:ro"
  backend:
    build:
      target: "backend"
    command: ["deno", "task", "start-dev"]
    volumes:
      - "./backend/src:/app/src:ro"
      - "./shared:/app/shared:ro"
      - "./backend/instances:/app/instances:ro"
    ports:
      - "127.0.0.1:9000:8000"
    environment:
      DATABASE_PASSWORD: "softres"
      DATABASE_USER: "softres"
      DISCORD_CLIENT_ID:
      DISCORD_CLIENT_SECRET:
      DISCORD_LOGIN_ENABLED: true
      DOMAIN: "localhost:8000"
      JWT_SECRET: "softres"
    depends_on:
      database:
        condition: "service_healthy"
  database:
    image: "postgres:18"
    command: [
      "postgres",
      "-c",
      "log_statement=all",
      "-c",
      "log_destination=stderr",
    ]
    environment:
      POSTGRES_PASSWORD: "softres"
      POSTGRES_USER: "softres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username softres"]
      interval: 1s
      timeout: 5s
      retries: 5
