services:
  backend:
    build:
      context: "."
      dockerfile: "backend/Dockerfile"
    command: ["deno", "task", "start-dev"]
    volumes:
      - ./backend/src:/app/src:ro
      - ./types:/app/types:ro
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      DATABASE_PASSWORD: "softres"
      DATABASE_USER: "softres"
    depends_on:
      database:
        condition: "service_healthy"
  database:
    image: "postgres:18"
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_PASSWORD: "softres"
      POSTGRES_USER: "softres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username softres"]
      interval: 1s
      timeout: 5s
      retries: 5
