name: All
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  json-validator:
    name: JSON validator
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Validate JSON files
        run: |
          for f in backend/instances/*.json; do
            if ! jq -e '.' "$f" > /dev/null; then
              echo "$f is invalid"
              exit 1
            fi
            echo "$f is valid"
          done
  frontend-types:
    name: Frontend Types
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: "deno install"
      - name: Types
        run: "deno check src"
  frontend-formatting:
    name: Frontend Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: "deno install"
      - name: Formatting
        run: "deno fmt --check src"
  backend-types:
    name: Backend Types
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "backend"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: "deno install"
      - name: Types
        run: "deno check src"
  backend-formatting:
    name: Backend Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "backend"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: "deno install"
      - name: Formatting
        run: "deno fmt --check src"

  build:
    name: Build
    if: github.ref == 'refs/heads/main'
    needs: [frontend-types, frontend-formatting, backend-types, backend-formatting, json-formatting]
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          tags: "${{env.REGISTRY}}/${{ github.repository }}:latest"
          context: .
          push: true
  deploy:
    name : Deploy
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Load deploy key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Update deployment
        run: 'ssh softres@softres.io -p 2026'
