name: All
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  frontend-types:
    name: Frontend Types
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: "deno install"
      - name: Types
        run: "deno check src"
  frontend-formatting:
    name: Frontend Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: "deno install"
      - name: Formatting
        run: "deno fmt --check src"
  backend-types:
    name: Backend Types
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "backend"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: "deno install"
      - name: Types
        run: "deno check src"
  backend-formatting:
    name: Backend Formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "backend"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: "deno install"
      - name: Formatting
        run: "deno fmt --check src"

  build-and-push-image:
    name: Build and push
    if: github.ref == 'refs/heads/main'
    needs: [frontend-types, frontend-formatting, backend-types, backend-formatting]
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          tags: "${{env.REGISTRY}}/${{ github.repository }}:latest"
          context: .
          push: true
